### ISSUE TITLE
hardcoded user folder references breaking build test process

### ISSUE THREAD

**Issue by chazzofalf** [kamranzafar/jtar#19]
During build package process in maven hard corded references to your user folder "/home/kamran" which do not exist anywhere except your machine (Hopefully) are causing the  tests to fail. It would be correct to refer to the $HOME variable instead so others can run the tests with out having them break.

**Comment by kamranzafar** [comment]
Thanks for pointing that out, I'll fix it.

**Comment by kamranzafar** [comment]
fixed in 2.3
