### ISSUE TITLE
long file name

### ISSUE THREAD

**Issue by mathieu-pousse** [kamranzafar/jtar#6]
After doing some tests, I spot that file name longer than 100 characters (including /) are truncated.

If I understand well it is because the header was not very flexible in the very first version of tar, but since 1988, ustar introduced a second area where we can store additional file prefix (http://en.wikipedia.org/wiki/Tar_%28file_format%29#UStar_format) after byte 345.

If you implement it the file name limitation will disappear and jtar will become the most famous tar utility

M.

**Comment by pkrouse** [comment]
I am using 2.3 and I am seeing the truncated file names when I untar my output.

Here is the code I am working with.  Am I doing something wrong?  Comments included for guidance.
public void tarFolder(String parent, String path, TarOutputStream out) throws Exception {
        BufferedInputStream origin = null;
        File f = new File( path );
        String files[] = f.list();

        // path is a single file instead of a directory
        if (files == null) {
            files = new String[1];
            files[0] = f.getName();
        }

        parent = ( ( parent == null ) ? ( f.isFile() ) ? "" : f.getName() + "/" : parent + f.getName() + "/" );

        for (int i = 0; i < files.length; i++) {
            //System.out.println( "Adding: " + files[i] );
            logger.info( "tar is adding: " + files[i] );
            File fe = f;
            byte data[] = new byte[BUFFER_SIZE];

            if (f.isDirectory()) {
                fe = new File( f, files[i] );
            }

            if (fe.isDirectory()) {
                String[] fl = fe.list();
                if (fl != null && fl.length != 0) {
                    tarFolder( parent, fe.getPath(), out );
                } else {
                    TarEntry entry = new TarEntry( fe, parent + files[i] + "/" );
                    out.putNextEntry( entry );
                }
                continue;
            }
            String peekatName = fe.getName();
            logger.info("file name after processing a little is "+peekatName); // names are fine here
            FileInputStream fi = new FileInputStream( fe );
            origin = new BufferedInputStream( fi );
            TarEntry entry = new TarEntry( fe, parent + files[i] );
            String entryName = entry.getName();
            logger.info("tarEntry version of that name is "+entryName); // names are still fine at this point
            out.putNextEntry( entry );

            int count;
            //int bc = 0;
            while (( count = origin.read( data ) ) != -1) {
                out.write( data, 0, count );
                //bc += count;
            }
            out.flush(); // the tarOutputStream has file names at a max of 100 chars when untarred later.
            origin.close();
        }
    }
